let sourceData;
const labels = { bulgarian: 'БЕЛ', math: 'МАТ', combined: 'Сумарен резултат' };
const gradePoints = { 6: 50, 5: 39, 4: 26, 3: 15 };
const gradeLabels = { 6: 'Отличен 6', 5: 'Много добър 5', 4: 'Добър 4', 3: 'Среден 3' };
const annualGrades = {};
const specialScores = {};
let visibleProgramCount = 10;
let inputs;
document.addEventListener('DOMContentLoaded', init);
function init() {
  inputs = {
    bulgarian: document.getElementById('bulgarianScore'), math: document.getElementById('mathScore'), gender: document.getElementById('gender'), combined: document.getElementById('combinedScore'), validation: document.getElementById('validation'), body: document.getElementById('resultsBody'), gradeOne: document.getElementById('gradeOne'), gradeTwo: document.getElementById('gradeTwo'), coefBulgarian: document.getElementById('coefBulgarian'), coefMath: document.getElementById('coefMath'), totalGradeScore: document.getElementById('totalGradeScore'), gradeValidation: document.getElementById('gradeValidation'), maxGradeNote: document.getElementById('maxGradeNote'), annualSubjectInputs: document.getElementById('annualSubjectInputs'), specialScoreInputs: document.getElementById('specialScoreInputs'), programResultsBody: document.getElementById('programResultsBody'), showMorePrograms: document.getElementById('showMorePrograms')
  };
  const required = ['bulgarian','math','gender','combined','validation','body','gradeOne','gradeTwo','coefBulgarian','coefMath','totalGradeScore','gradeValidation','maxGradeNote','annualSubjectInputs','specialScoreInputs','programResultsBody','showMorePrograms'];
  const missing = required.filter(key => !inputs[key]);
  if (missing.length) { document.body.insertAdjacentHTML('afterbegin', '<p class="load-error">Липсващи HTML елементи: ' + missing.join(', ') + '</p>'); return; }
  inputs.bulgarian.addEventListener('input', () => { resetProgramCount(); update(); });
  inputs.math.addEventListener('input', () => { resetProgramCount(); update(); });
  inputs.gender.addEventListener('change', () => { resetProgramCount(); update(); });
  inputs.gradeOne.addEventListener('change', updateTotalGrade);
  inputs.gradeTwo.addEventListener('change', updateTotalGrade);
  inputs.coefBulgarian.addEventListener('input', syncCoefMathFromBulgarian);
  inputs.showMorePrograms.addEventListener('click', handleShowMorePrograms);
  document.querySelectorAll('input[name="quotaFilter"]').forEach(r => r.addEventListener('change', () => { resetProgramCount(); updatePrograms(); }));
  document.querySelectorAll('input[name="studentGender"]').forEach(r => r.addEventListener('change', () => { resetProgramCount(); updatePrograms(); }));
  fetch('data.json').then(r => r.json()).then(data => { sourceData = data; validateData(data); buildProgramInputs(); update(); }).catch(error => { inputs.validation.textContent = 'Данните не можаха да бъдат заредени: ' + error.message; console.error(error); });
}
function validateData(data) { if (!Array.isArray(data.rows) || !data.totals) throw new Error('липсват rows/totals'); if (!Array.isArray(data.programs)) data.programs = []; if (!Array.isArray(data.annualSubjects)) data.annualSubjects = []; if (!Array.isArray(data.specialSubjects)) data.specialSubjects = []; }
function syncCoefMathFromBulgarian() { const c = Number(inputs.coefBulgarian.value); if (validCoefficient(c)) inputs.coefMath.value = String(4 - c); updateTotalGrade(); }
function resetProgramCount() { visibleProgramCount = 10; }
function handleShowMorePrograms(event) { if (event) event.preventDefault(); visibleProgramCount += 10; updatePrograms(); }
function update() { const b = Number(inputs.bulgarian.value); const m = Number(inputs.math.value); const combined = roundTo2(b + m); inputs.combined.value = Number.isFinite(combined) ? combined.toFixed(2) : ''; updateTotalGrade(); if (!sourceData) return; if (!validScore(b) || !validScore(m)) { inputs.validation.textContent = 'Въведете резултати между 0 и 100.'; inputs.body.innerHTML = ''; inputs.programResultsBody.innerHTML = '<tr><td colspan="9">Въведете валидни точки по БЕЛ и МАТ.</td></tr>'; return; } inputs.validation.textContent = ''; const g = inputs.gender.value; const rows = [buildResult('bulgarian', b, g), buildResult('math', m, g), buildResult('combined', combined, g)]; inputs.body.innerHTML = rows.map(row => '<tr><td>' + row.label + '</td><td>' + formatScore(row.score) + ' (' + row.band + ')</td><td>' + formatInt(row.count) + '</td><td>' + formatInt(row.above) + '</td><td class="rank">#' + formatInt(row.rankFrom) + '–' + formatInt(row.rankTo) + '</td><td>' + formatInt(row.total) + '</td><td>Топ ' + row.topFrom + '%–' + row.topTo + '%</td></tr>').join(''); updatePrograms(); }
function updateTotalGrade() { if (!inputs) return; const b = Number(inputs.bulgarian.value); const m = Number(inputs.math.value); const g1 = Number(inputs.gradeOne.value); const g2 = Number(inputs.gradeTwo.value); const cb = Number(inputs.coefBulgarian.value); const cm = Number(inputs.coefMath.value); updateGradeNote(cb, cm, g1, g2); if (!validScore(b) || !validScore(m) || !validCoefficient(cb) || !validCoefficient(cm) || cb + cm !== 4) { inputs.gradeValidation.textContent = 'Коефициентите трябва да са цели числа от 1 до 3 и сборът им да е точно 4.'; inputs.totalGradeScore.textContent = '—'; return; } inputs.gradeValidation.textContent = ''; inputs.totalGradeScore.textContent = formatNumber(roundTo2(b * cb + m * cm + gradePoints[g1] + gradePoints[g2])); updatePrograms(); }
function updateGradeNote(cb, cm, g1, g2) { if (!validCoefficient(cb) || !validCoefficient(cm) || cb + cm !== 4) return; inputs.maxGradeNote.textContent = 'макс. ' + formatNumber(100 * cb + 100 * cm + gradePoints[g1] + gradePoints[g2]) + ' при коефициенти ' + cb + ' + ' + cm + ' и годишни оценки ' + gradeLabels[g1] + ' + ' + gradeLabels[g2]; }
function buildProgramInputs() { inputs.annualSubjectInputs.innerHTML = ''; inputs.specialScoreInputs.innerHTML = ''; sourceData.annualSubjects.forEach(s => { annualGrades[s] = annualGrades[s] || '6'; const label = document.createElement('label'); label.textContent = s; const select = document.createElement('select'); [6,5,4,3].forEach(g => { const o = document.createElement('option'); o.value = String(g); o.textContent = gradeLabels[g] + ' → ' + gradePoints[g] + ' т.'; select.appendChild(o); }); select.value = annualGrades[s]; select.addEventListener('change', () => { annualGrades[s] = select.value; updatePrograms(); }); label.appendChild(select); inputs.annualSubjectInputs.appendChild(label); }); sourceData.specialSubjects.forEach(s => { specialScores[s] = specialScores[s] || 0; const label = document.createElement('label'); label.textContent = s; const input = document.createElement('input'); input.type = 'number'; input.min = '0'; input.max = '100'; input.step = '0.01'; input.value = specialScores[s]; input.addEventListener('input', () => { specialScores[s] = Math.max(0, Math.min(100, Number(input.value) || 0)); updatePrograms(); }); label.appendChild(input); inputs.specialScoreInputs.appendChild(label); }); }
function updatePrograms() { if (!sourceData || !Array.isArray(sourceData.programs) || !inputs.programResultsBody) return; const b = Number(inputs.bulgarian.value); const m = Number(inputs.math.value); if (!validScore(b) || !validScore(m)) return; const selected = document.querySelector('input[name="quotaFilter"]:checked'); const gender = document.querySelector('input[name="studentGender"]:checked'); const filter = selected ? selected.value : 'all'; const studentGender = gender ? gender.value : 'boys'; const programs = sourceData.programs.map(p => { const score = scoreProgram(p.formula, b, m); const cutoffKey = isQuota(p.quotas) ? studentGender : 'overall'; const cutoff = Number(p.min && (p.min[cutoffKey] || p.min.overall)); return { ...p, score, cutoff, margin: score - cutoff }; }).filter(p => Number.isFinite(p.cutoff) && p.margin >= 0).filter(p => filter === 'all' || (filter === 'quotas' ? isQuota(p.quotas) : isNoQuota(p.quotas))).sort((a, b) => b.cutoff - a.cutoff); if (!programs.length) { inputs.programResultsBody.innerHTML = '<tr><td colspan="9">Няма паралелки, които отговарят на избрания филтър и текущия бал.</td></tr>'; inputs.showMorePrograms.hidden = true; return; } const visible = programs.slice(0, visibleProgramCount); inputs.programResultsBody.innerHTML = visible.map(p => '<tr><td>' + escapeHtml(p.rankNo) + '</td><td>' + escapeHtml(p.school) + '</td><td>' + escapeHtml(p.program) + '</td><td>' + escapeHtml(formatQuota(p.quotas)) + '</td><td>' + formatNumber(roundTo2(p.score)) + '</td><td>' + formatNumber(p.cutoff) + '</td><td>' + formatNumber(roundTo2(p.margin)) + '</td><td class="formula-cell">' + escapeHtml(p.formula || '—') + '</td><td>' + escapeHtml(p.code) + '</td></tr>').join(''); const remaining = Math.max(0, programs.length - visibleProgramCount); inputs.showMorePrograms.hidden = false; inputs.showMorePrograms.disabled = remaining === 0; inputs.showMorePrograms.textContent = remaining === 0 ? 'Показани са всички ' + programs.length + ' резултата' : 'Покажи още (' + Math.min(10, remaining) + ')'; }
function scoreProgram(method, b, m) { const alternatives = String(method || '').split(/\s+или\s+/i).map(x => x.trim()).filter(Boolean); return Math.max(...alternatives.map(x => scoreAlternative(x, b, m)), 0); }
function scoreAlternative(text, b, m) { const groups = [...String(text).matchAll(/\(([^()]*)\)/g)].map(x => x[1]); return sumTerms(groups[0] || text, 'exam', b, m) + sumTerms(groups.slice(1).join(' + '), 'annual', b, m); }
function sumTerms(text, type, b, m) { let total = 0; const re = /(\d+(?:[.,]\d+)?)\s*\*\s*([^+()]+)/g; let match; while ((match = re.exec(String(text))) !== null) total += Number(String(match[1]).replace(',', '.')) * valueForToken(String(match[2]).trim().replace(/\s+/g, ' '), type, b, m); return total; }
function valueForToken(token, type, b, m) { if (type === 'exam') { if (token === 'БЕЛ') return b; if (token === 'МАТ') return m; return Number(specialScores[token] || 0); } return gradePoints[Number(annualGrades[token] || 6)] || 0; }
function buildResult(metric, score, gender) { const row = findBand(score); const stat = row[metric][gender]; const total = sourceData.totals[metric][gender]; const rankFrom = stat.above + 1; const rankTo = stat.above + stat.count; return { label: labels[metric], score, band: row.band, count: stat.count, above: stat.above, total, rankFrom, rankTo, topFrom: ((rankFrom / total) * 100).toFixed(1), topTo: ((rankTo / total) * 100).toFixed(1) }; }
function findBand(score) { const targetStart = Math.floor(score * 2) / 2; const match = sourceData.rows.find(row => { const parsed = parseBand(row.band); return parsed && targetStart >= parsed.min && targetStart <= parsed.max; }); return match || sourceData.rows[sourceData.rows.length - 1]; }
function parseBand(band) { const parts = String(band).split(' - ').map(Number); if (parts.length === 2 && parts.every(Number.isFinite)) return { min: parts[0], max: parts[1] }; const exact = Number(band); return Number.isFinite(exact) ? { min: exact, max: exact } : null; }
function isQuota(value) { return value === 'С квоти' || value === 'Quotas'; }
function isNoQuota(value) { return value === 'Без квоти' || value === 'No quotas'; }
function formatQuota(value) { return isQuota(value) ? 'С квоти' : isNoQuota(value) ? 'Без квоти' : value; }
function validScore(value) { return Number.isFinite(value) && value >= 0 && value <= 100; }
function validCoefficient(value) { return Number.isInteger(value) && value >= 1 && value <= 3; }
function roundTo2(value) { return Math.round(value * 100) / 100; }
function formatInt(value) { return new Intl.NumberFormat('bg-BG').format(value); }
function formatScore(value) { return new Intl.NumberFormat('bg-BG', { maximumFractionDigits: 2 }).format(value); }
function formatNumber(value) { return new Intl.NumberFormat('bg-BG', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value); }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch])); }
