let sourceData;
let inputs;
let visibleProgramCount = 10;
const labels = { bulgarian: 'БЕЛ', math: 'МАТ', combined: 'Сумарен резултат' };
const gradePoints = { 6: 50, 5: 39, 4: 26, 3: 15 };
const gradeLabels = { 6: 'Отличен 6', 5: 'Много добър 5', 4: 'Добър 4', 3: 'Среден 3' };
const annualGrades = {};
const annualGradeOverrides = {};
const specialGrades = {};
document.addEventListener('DOMContentLoaded', init);
function init() { inputs = { bulgarian: el('bulgarianScore'), math: el('mathScore'), gender: el('gender'), combined: el('combinedScore'), validation: el('validation'), body: el('resultsBody'), gradeOne: el('gradeOne'), gradeTwo: el('gradeTwo'), coefBulgarian: el('coefBulgarian'), coefMath: el('coefMath'), totalGradeScore: el('totalGradeScore'), gradeValidation: el('gradeValidation'), maxGradeNote: el('maxGradeNote'), annualSubjectInputs: el('annualSubjectInputs'), specialScoreInputs: el('specialScoreInputs'), programResultsBody: el('programResultsBody'), showMorePrograms: el('showMorePrograms') }; const missing = Object.keys(inputs).filter(k => !inputs[k]); if (missing.length) { document.body.insertAdjacentHTML('afterbegin', '<p class="load-error">Липсващи HTML елементи: ' + missing.join(', ') + '</p>'); return; } attachEvents(); fetch('data.json').then(r => r.json()).then(data => { sourceData = normalizeData(data); buildProgramInputs(); update(); }).catch(error => { inputs.validation.textContent = 'Данните не можаха да бъдат заредени: ' + error.message; console.error(error); }); }
function el(id) { return document.getElementById(id); }
function attachEvents() { inputs.bulgarian.addEventListener('input', () => { resetProgramCount(); update(); }); inputs.math.addEventListener('input', () => { resetProgramCount(); update(); }); inputs.gender.addEventListener('change', () => { resetProgramCount(); update(); }); inputs.gradeOne.addEventListener('change', () => { syncAnnualDefaultsFromMainGrades(); updateTotalGrade(); }); inputs.gradeTwo.addEventListener('change', () => { syncAnnualDefaultsFromMainGrades(); updateTotalGrade(); }); inputs.coefBulgarian.addEventListener('input', syncCoefMathFromBulgarian); inputs.showMorePrograms.addEventListener('click', handleShowMorePrograms); document.querySelectorAll('input[name="quotaFilter"]').forEach(r => r.addEventListener('change', () => { resetProgramCount(); updatePrograms(); })); document.querySelectorAll('input[name="studentGender"]').forEach(r => r.addEventListener('change', () => { resetProgramCount(); updatePrograms(); })); }
function normalizeData(data) { if (!Array.isArray(data.rows) || !data.totals) throw new Error('липсват rows/totals'); data.programs = Array.isArray(data.programs) ? data.programs : []; data.annualSubjects = Array.isArray(data.annualSubjects) ? data.annualSubjects : []; data.specialSubjects = Array.isArray(data.specialSubjects) ? data.specialSubjects : []; return data; }
function syncCoefMathFromBulgarian() { const c = Number(inputs.coefBulgarian.value); if (validCoefficient(c)) inputs.coefMath.value = String(4 - c); updateTotalGrade(); }
function resetProgramCount() { visibleProgramCount = 10; }
function handleShowMorePrograms(event) { if (event) event.preventDefault(); visibleProgramCount += 10; updatePrograms(); }
function update() { const b = Number(inputs.bulgarian.value); const m = Number(inputs.math.value); const combined = roundTo2(b + m); inputs.combined.value = Number.isFinite(combined) ? combined.toFixed(2) : ''; updateTotalGrade(); if (!sourceData) return; if (!validScore(b) || !validScore(m)) { inputs.validation.textContent = 'Въведете резултати между 0 и 100.'; inputs.body.innerHTML = ''; inputs.programResultsBody.innerHTML = '<tr><td colspan="9">Въведете валидни точки по БЕЛ и МАТ.</td></tr>'; return; } inputs.validation.textContent = ''; const g = inputs.gender.value; const rows = [buildResult('bulgarian', b, g), buildResult('math', m, g), buildResult('combined', combined, g)]; inputs.body.innerHTML = rows.map(row => '<tr><td>' + row.label + '</td><td>' + formatScore(row.score) + ' (' + row.band + ')</td><td>' + formatInt(row.count) + '</td><td>' + formatInt(row.above) + '</td><td class="rank">#' + formatInt(row.rankFrom) + '–' + formatInt(row.rankTo) + '</td><td>' + formatInt(row.total) + '</td><td>Топ ' + row.topFrom + '%–' + row.topTo + '%</td></tr>').join(''); updatePrograms(); }
function updateTotalGrade() { if (!inputs) return; const b = Number(inputs.bulgarian.value); const m = Number(inputs.math.value); const g1 = Number(inputs.gradeOne.value); const g2 = Number(inputs.gradeTwo.value); const cb = Number(inputs.coefBulgarian.value); const cm = Number(inputs.coefMath.value); updateGradeNote(cb, cm, g1, g2); if (!validScore(b) || !validScore(m) || !validCoefficient(cb) || !validCoefficient(cm) || cb + cm !== 4) { inputs.gradeValidation.textContent = 'Коефициентите трябва да са цели числа от 1 до 3 и сборът им да е точно 4.'; inputs.totalGradeScore.textContent = '—'; return; } inputs.gradeValidation.textContent = ''; inputs.totalGradeScore.textContent = formatNumber(roundTo2(b * cb + m * cm + gradePoints[g1] + gradePoints[g2])); updatePrograms(); }
function updateGradeNote(cb, cm, g1, g2) { if (!inputs.maxGradeNote) return; if (!validCoefficient(cb) || !validCoefficient(cm) || cb + cm !== 4 || !gradePoints[g1] || !gradePoints[g2]) { inputs.maxGradeNote.textContent = 'балът се изчислява след валидни коефициенти и оценки'; return; } const maxScore = 100 * cb + 100 * cm + gradePoints[g1] + gradePoints[g2]; inputs.maxGradeNote.textContent = 'макс. ' + formatNumber(maxScore) + ' при коефициенти ' + cb + ' + ' + cm + ' и годишни оценки ' + gradeLabels[g1] + ' + ' + gradeLabels[g2] + '. Тези оценки се използват като подразбиране за предметите във формулите по паралелки, докато не въведете конкретна оценка от специален предмет.'; }
function defaultDiplomaGrade(subject) { const mathLike = new Set(['М','ФА','КМИТ','ТП','МиФВС']); return mathLike.has(subject) ? String(inputs.gradeTwo.value || '6') : String(inputs.gradeOne.value || '6'); }
function syncAnnualDefaultsFromMainGrades() { if (!sourceData) return; sourceData.annualSubjects.forEach(s => { if (!annualGradeOverrides[s]) annualGrades[s] = defaultDiplomaGrade(s); }); document.querySelectorAll('[data-annual-subject]').forEach(select => { const s = select.getAttribute('data-annual-subject'); if (!annualGradeOverrides[s]) select.value = annualGrades[s]; }); }
function isNpmgToken(token) { return String(token || '').startsWith('НПМГ'); }
function buildProgramInputs() { inputs.annualSubjectInputs.innerHTML = ''; inputs.specialScoreInputs.innerHTML = ''; sourceData.annualSubjects.forEach(s => { annualGrades[s] = annualGrades[s] || defaultDiplomaGrade(s); const label = document.createElement('label'); label.textContent = s; const select = document.createElement('select'); select.setAttribute('data-annual-subject', s); [6,5,4,3].forEach(g => { const o = document.createElement('option'); o.value = String(g); o.textContent = gradeLabels[g] + ' → ' + gradePoints[g] + ' т.'; select.appendChild(o); }); select.value = annualGrades[s]; select.addEventListener('change', () => { annualGradeOverrides[s] = true; annualGrades[s] = select.value; updatePrograms(); }); label.appendChild(select); inputs.annualSubjectInputs.appendChild(label); }); sourceData.specialSubjects.forEach(s => { const label = document.createElement('label'); label.textContent = s; if (isNpmgToken(s)) { specialGrades[s] = specialGrades[s] || '0'; const input = document.createElement('input'); input.type = 'number'; input.min = '0'; input.max = '100'; input.step = '0.01'; input.value = specialGrades[s]; input.addEventListener('input', () => { specialGrades[s] = String(Math.max(0, Math.min(100, Number(input.value) || 0))); updatePrograms(); }); label.appendChild(input); } else { specialGrades[s] = specialGrades[s] || '6'; const select = document.createElement('select'); [6,5,4,3].forEach(g => { const o = document.createElement('option'); o.value = String(g); o.textContent = gradeLabels[g] + ' → ' + gradePoints[g] + ' т.'; select.appendChild(o); }); select.value = specialGrades[s]; select.addEventListener('change', () => { specialGrades[s] = select.value; updatePrograms(); }); label.appendChild(select); } inputs.specialScoreInputs.appendChild(label); }); syncAnnualDefaultsFromMainGrades(); }
function updatePrograms() { if (!sourceData || !Array.isArray(sourceData.programs) || !inputs.programResultsBody) return; const b = Number(inputs.bulgarian.value); const m = Number(inputs.math.value); if (!validScore(b) || !validScore(m)) return; const selected = document.querySelector('input[name="quotaFilter"]:checked'); const gender = document.querySelector('input[name="studentGender"]:checked'); const filter = selected ? selected.value : 'all'; const studentGender = gender ? gender.value : 'boys'; const programs = sourceData.programs.map(p => { const score = scoreProgram(p.formula, b, m); const cutoffKey = isQuota(p.quotas) ? studentGender : 'overall'; const cutoff = Number(p.min && (p.min[cutoffKey] || p.min.overall)); return { ...p, score, cutoff, margin: score - cutoff }; }).filter(p => Number.isFinite(p.cutoff) && p.margin >= 0).filter(p => filter === 'all' || (filter === 'quotas' ? isQuota(p.quotas) : isNoQuota(p.quotas))).sort((a, b) => b.cutoff - a.cutoff); if (!programs.length) { inputs.programResultsBody.innerHTML = '<tr><td colspan="9">Няма паралелки, които отговарят на избрания филтър и текущия бал.</td></tr>'; inputs.showMorePrograms.hidden = true; return; } const visible = programs.slice(0, visibleProgramCount); inputs.programResultsBody.innerHTML = visible.map(p => '<tr><td>' + escapeHtml(p.rankNo) + '</td><td>' + escapeHtml(p.school) + '</td><td>' + escapeHtml(p.program) + '</td><td>' + escapeHtml(formatQuota(p.quotas)) + '</td><td>' + formatNumber(roundTo2(p.score)) + '</td><td>' + formatNumber(p.cutoff) + '</td><td>' + formatNumber(roundTo2(p.margin)) + '</td><td class="formula-cell">' + escapeHtml(p.formula || '—') + '</td><td>' + escapeHtml(p.code) + '</td></tr>').join(''); const remaining = Math.max(0, programs.length - visibleProgramCount); inputs.showMorePrograms.hidden = false; inputs.showMorePrograms.disabled = remaining === 0; inputs.showMorePrograms.textContent = remaining === 0 ? 'Показани са всички ' + programs.length + ' резултата' : 'Покажи още (' + Math.min(10, remaining) + ')'; }
function scoreProgram(method, b, m) { const alternatives = String(method || '').split(/\s+или\s+/i).map(x => x.trim()).filter(Boolean); return Math.max(...alternatives.map(x => scoreAlternative(x, b, m)), 0); }
function scoreAlternative(text, b, m) { const groups = [...String(text).matchAll(/\(([^()]*)\)/g)].map(x => x[1]); return sumTerms(groups[0] || text, 'exam', b, m) + sumTerms(groups.slice(1).join(' + '), 'annual', b, m); }
function sumTerms(text, type, b, m) { let total = 0; const re = /(\d+(?:[.,]\d+)?)\s*\*\s*([^+()]+)/g; let match; while ((match = re.exec(String(text))) !== null) total += Number(String(match[1]).replace(',', '.')) * valueForToken(String(match[2]).trim().replace(/\s+/g, ' '), type, b, m); return total; }
function valueForToken(token, type, b, m) { if (type === 'exam') { if (token === 'БЕЛ') return b; if (token === 'МАТ') return m; if (isNpmgToken(token)) return Math.max(0, Math.min(100, Number(specialGrades[token]) || 0)); return gradePoints[Number(specialGrades[token] || 6)] || 0; } return gradePoints[Number(annualGrades[token] || defaultDiplomaGrade(token))] || 0; }
function buildResult(metric, score, gender) { const row = findBand(score); const stat = row[metric][gender]; const total = sourceData.totals[metric][gender]; const rankFrom = stat.above + 1; const rankTo = stat.above + stat.count; return { label: labels[metric], score, band: row.band, count: stat.count, above: stat.above, total, rankFrom, rankTo, topFrom: ((rankFrom / total) * 100).toFixed(1), topTo: ((rankTo / total) * 100).toFixed(1) }; }
function findBand(score) { const targetStart = Math.floor(score * 2) / 2; const match = sourceData.rows.find(row => { const parsed = parseBand(row.band); return parsed && targetStart >= parsed.min && targetStart <= parsed.max; }); return match || sourceData.rows[sourceData.rows.length - 1]; }
function parseBand(band) { const parts = String(band).split(' - ').map(Number); if (parts.length === 2 && parts.every(Number.isFinite)) return { min: parts[0], max: parts[1] }; const exact = Number(band); return Number.isFinite(exact) ? { min: exact, max: exact } : null; }
function isQuota(value) { return value === 'С квоти' || value === 'Quotas'; }
function isNoQuota(value) { return value === 'Без квоти' || value === 'No quotas'; }
function formatQuota(value) { return isQuota(value) ? 'С квоти' : isNoQuota(value) ? 'Без квоти' : value; }
function validScore(value) { return Number.isFinite(value) && value >= 0 && value <= 100; }
function validCoefficient(value) { return Number.isInteger(value) && value >= 1 && value <= 3; }
function roundTo2(value) { return Math.round(value * 100) / 100; }
function formatInt(value) { return new Intl.NumberFormat('bg-BG').format(value); }
function formatScore(value) { return new Intl.NumberFormat('bg-BG', { maximumFractionDigits: 2 }).format(value); }
function formatNumber(value) { return new Intl.NumberFormat('bg-BG', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value); }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch])); }
